# Generated by Django 3.2 on 2021-04-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('desc', models.TextField()),
                ('genre', models.CharField(choices=[('Horror', 'Horror'), ('Thriller', 'Thriller'), ('Romantic', 'Romantic')], max_length=20)),
                ('condition', models.CharField(choices=[('Good', 'G'), ('Average', 'A'), ('Poor', 'P')], max_length=8)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
