# Generated by Django 3.2 on 2021-05-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='displayname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
